### PR TITLE
Chromium11

### PR DESCRIPTION
**Pull request by Matt1360**
This is just an added patch to work on boxes with >=libpng-1.5.  I work on a Gentoo box, and the default slot in portage is 1.5.8, we stop getting direct access to the png_struct.  This _should_ work on anything older as well, but I recommend testing it first.  I meant to send this in with my last pull request, but didn't think of it until I needed to build Berkelium on a new machine.

Thanks!

### CODE REVIEW

**Comment by ewencp** [comment]
I'm getting these errors:

```
third_party/WebKit/Source/WebCore/platform/image-decoders/png/PNGImageDecoder.cpp: In function ‘WebCore::ColorProfile WebCore::readColorProfile(png_struct*, png_info*)’:
third_party/WebKit/Source/WebCore/platform/image-decoders/png/PNGImageDecoder.cpp:231: error: invalid conversion from ‘png_byte**’ to ‘char**’
third_party/WebKit/Source/WebCore/platform/image-decoders/png/PNGImageDecoder.cpp:231: error:   initializing argument 5 of ‘png_uint_32 png_get_iCCP(png_struct*, png_info*, char**, int*, char**, png_uint_32*)’
third_party/WebKit/Source/WebCore/platform/image-decoders/png/PNGImageDecoder.cpp: In member function ‘void WebCore::PNGImageDecoder::headerAvailable()’:
third_party/WebKit/Source/WebCore/platform/image-decoders/png/PNGImageDecoder.cpp:322: error: ‘png_process_data_pause’ was not declared in this scope
```

I don't think you can get compatibility with both versions unless you use some ifdefs to select which versions of calls you make based on the version/features of libpng.

**Comment by Matt1360** [comment]
Alright, I'll wrap those bits with a check for PNG_LIBPNG_VER_MAJOR >= 1 && PNG_LIBPNG_VER_MINOR >= 5, if you think that's acceptable.

**Comment by ewencp** [comment]
Sounds good.

**Comment by Matt1360** [comment]
I pushed the change.  I hope this fixes it for you.

**Comment by ewencp** [comment]
Looks good to me now.
