### ISSUE TITLE
chromium compile errors on linux

### ISSUE THREAD

**Issue by jarrettchisholm** [sirikata/berkelium#18]
Several compile errors arise when compiling chromium on linux (Debian testing, 64bit, gcc 4.7.1, cmake 2.8.9).

This is the first error received (this same type of error seems to appear in other files as well):

```
In file included from ui/base/ui_base_paths.cc:9:0:
./base/file_util.h: In member function ‘void file_util::ScopedFDClose::operator()(int*) const’:
./base/file_util.h:380:11: error: ‘close’ was not declared in this scope
./base/file_util.h:380:11: error: invalid type in declaration before ‘;’ token
In file included from app/app_paths.cc:9:0:
./base/file_util.h: In member function ‘void file_util::ScopedFDClose::operator()(int*) const’:
./base/file_util.h:380:11: error: ‘close’ was not declared in this scope
./base/file_util.h:380:11: error: invalid type in declaration before ‘;’ token
make: *** [out/Release/obj.target/app_base/ui/base/ui_base_paths.o] Error 1
make: *** [out/Release/obj.target/app_base/app/app_paths.o] Error 1
In file included from ui/base/l10n/l10n_util.cc:17:0:
./base/file_util.h: In member function ‘void file_util::ScopedFDClose::operator()(int*) const’:
./base/file_util.h:380:11: error: ‘close’ was not declared in this scope
./base/file_util.h:380:11: error: invalid type in declaration before ‘;’ token
make: *** [out/Release/obj.target/app_base/ui/base/l10n/l10n_util.o] Error 1
In file included from chrome/utility/utility_main.cc:7:0:
./base/file_util.h: In member function ‘void file_util::ScopedFDClose::operator()(int*) const’:
./base/file_util.h:380:11: error: ‘close’ was not declared in this scope
./base/file_util.h:380:11: error: invalid type in declaration before ‘;’ token
In file included from chrome/utility/utility_thread.cc:9:0:
./base/file_util.h: In member function ‘void file_util::ScopedFDClose::operator()(int*) const’:
./base/file_util.h:380:11: error: ‘close’ was not declared in this scope
./base/file_util.h:380:11: error: invalid type in declaration before ‘;’ token
make: *** [out/Release/obj.target/utility/chrome/utility/utility_main.o] Error 1
make: *** [out/Release/obj.target/utility/chrome/utility/utility_thread.o] Error 1
Failed to install: chromium
```

**Solution**:
Need to include unistd.h in files where this error occurs (POSIX specific error I think).
so, these files need this line:
`#include <unistd.h>`

Related to this error (chromium build using gcc 4.7): http://code.google.com/p/chromium/issues/detail?id=120724

I don't have push priveleges, so I can't push back my changes (I also don't quite get the whole push request thing.. :)
